### ISSUE TITLE
Ril.

### ISSUE THREAD

**Issue by Kcrams** [BambooIV/android_device_zte_nx503a#1]
Hi bamboo, with cm 13.0 ril works on my device, so thank you :D the only thing that isnt working in sd storage, the phone doesnt detect the sd card, i remember that one week ago ,i was compiling your cm 13.0 code and the phone detected the correct sdcard partition, so maybe, is H213 sdscheme that caused the issue?

**Comment by BambooIV** [comment]
no idea,and don't know how to fix this...

**Comment by Kcrams** [comment]
I wanto to try 2 o 3 mods for sdcard, i'll write it later if i will fix it

**Comment by Kcrams** [comment]
Btw i'll try to modify the fstabs and sdcard files like this commit https://github.com/PaoloW8/android_device_nubia_nx505j/commit/3611a24742b6ef1c49266e2c177a80d36b874876 (for nx505j)

**Comment by BambooIV** [comment]
check these out:
https://github.com/CyanogenMod/android_device_lge_hammerheadcaf/commit/d9fbe911885f3364f833c30a33eaeac7e6dc3d40
https://github.com/KonstaT/android_device_zte_kis3/commit/de98153c4c38633d6520cdfa9ecee17f7164298f

**Comment by Kcrams** [comment]
It's the same, i will try right now
